plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    // Runtime dependencies for the normal Fabric JAR.
    implementation 'org.javassist:javassist:3.29.2-GA'
    implementation 'org.ow2.asm:asm:9.7.1'
    implementation 'org.ow2.asm:asm-tree:9.7.1'
    implementation 'org.ow2.asm:asm-analysis:9.7.1'
    implementation 'org.ow2.asm:asm-util:9.7.1'
    implementation 'org.ow2.asm:asm-commons:9.7.1'
    implementation 'com.google.guava:guava:17.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'io.netty:netty-all:4.0.23.Final'
    implementation 'commons-io:commons-io:2.4'
    implementation 'org.lwjgl.lwjgl:lwjgl:2.9.3'
    implementation 'org.lwjgl.lwjgl:lwjgl_util:2.9.3'
    compileOnly 'org.jetbrains:annotations:24.1.0'

}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
    options.compilerArgs += ['-Xmaxerrs', '10000', '-Xdiags:verbose']
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

jar {
    archiveFileName = 'Vapor-FabricMC26.2_v4.21.jar'
    from('LICENSE') {
        rename { "${it}_${project.name}" }
    }
    manifest {
        attributes(
                'Implementation-Title': 'Vapor 4.21 Fabric client mod',
                'Implementation-Version': project.version)
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
